services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: population_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - population_service_network


  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@postgres/population_db
      SOURCE_URL: https://en.wikipedia.org/w/index.php?title=List_of_countries_by_population_(United_Nations)&oldid=1215058959
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - population_service_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000


  get_data:
    build: .
    volumes:
      - .:/app
    depends_on:
      - app
    command: curl -X POST http://app:8000/get_data
    networks:
      - population_service_network


  print_data:
    build: .
    volumes:
      - .:/app
    depends_on:
      - app
    command: curl http://app:8000/print_data
    networks:
      - population_service_network


volumes:
  postgres_data: {}

networks:
  population_service_network:
    driver: bridge

