services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: population_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build: .
    environment:
      DATABASE_URL: postgresql://user:password@postgres/population_db
      SOURCE_URL: https://en.wikipedia.org/w/index.php?title=List_of_countries_by_population_(United_Nations)&oldid=1215058959
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
      - 8.8.4.4


  get_data:
    build: .
    volumes:
      - .:/app
    command: curl -X POST http://web:8000/get_data


  print_data:
    build: .
    volumes:
      - .:/app
    command: curl http://web:8000/print_data


volumes:
  postgres_data: { }

networks:
  population_service_default:
    external: true
